### ISSUE TITLE
Market Row UX

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-community-ui#119]
![image](https://user-images.githubusercontent.com/33128181/47649977-200f4000-db7f-11e8-8e4f-9e357af1d4cb.png)

Was this layout discussed somewhere?

**Comment by roma219** [comment]
No it wasn't

@sschiessl-bcp Please add labels to your issues e.g. "question"

**Comment by sschiessl-bcp** [comment]
In general I would say: KISS

My 2 cents:
 - volume under market is weird
 - try to not have multiple rows within one market row
 - what do the two percents mean?
 - USD could be optional (I got confused)
 - if in doubt how to do it, do it like binance :)

**Comment by roma219** [comment]
@hisinbox @dls-cipher @noeminik

**Comment by dls-cipher** [comment]
> @hisinbox @dls-cipher @noeminik

Thanks. 

@sschiessl-bcp 

-Responsive needs more tweaking up and font weight is definitely weird. 
- We don't use spacers/lines so we can achieve best compromises in responsive without breaking screens in pieces. 
- 2 percents are described in top row (24h and 7d), so one represent the change of 24h and one of 7days. I do agree it's confusing and too much info and it needs to be more simplified. Maybe a default of 24h, where on click it can switch to 7 days would be better ?
- Stake-holders in initial discussion requested USD value to be visible like on any usual CEX. 
- 2-edge sword. Even though I personally love UX in app, website and mobile for Binance, I also know they are looking for DEX version of it, and this is a bit open-source which would not be good to look like Binance :) Because of that we accepted more design ideas from Bitfinex and Huobi as mentioned in original worker. 

I hope my reply is ok. Would love to see more progress on this discussion. Definitely there are smaller issues to be addressed and your input has proven to be very valuable until now :)

**Comment by sschiessl-bcp** [comment]
> - We don't use spacers/lines so we can achieve best compromises in responsive without breaking screens in pieces.

What do you mean?

> Maybe a default of 24h, where on click it can switch to 7 days would be better ?

Rather switch between that and volume, or all three

> I also know they are looking for DEX version of it

It shouldn't look exactly like Binance of course

**Comment by dls-cipher** [comment]
![image](https://user-images.githubusercontent.com/39482961/47835805-4ed42300-ddd8-11e8-9538-324d36af14fa.png)
